#!/bin/sh
 "$(dirname "$0")/_/husky.sh"

yarn test --watchAll=false

yarn run check-types ||
{
  echo 'Failed tsc!'
  false;
}

yarn run check-format ||
{
  echo 'Failed prettier!'
  false;
}


yarn run check-lint ||
{
  echo 'Failed eslint!'
  false;
}



